# Generated by Django 5.2.3 on 2025-07-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('ADMIN', 'ADMIN')], max_length=10),
        ),
    ]
